export const emojis = [
    { name: "Zap", icon: "⚡", value: ":zap:" },
    { name: "Bug", icon: "🐛", value: ":bug:" },
    { name: "Sparkles", icon: "✨", value: ":sparkles:" },
    { name: "Rocket", icon: "🚀", value: ":rocket:" },
    { name: "Memo", icon: "📝", value: ":memo:" },
    { name: "Lipstick", icon: "💄", value: ":lipstick:" },
    { name: "Tada", icon: "🎉", value: ":tada:" },
    { name: "Check Mark", icon: "✅", value: ":white_check_mark:" },
    { name: "Bookmark", icon: "🔖", value: ":bookmark:" },
    { name: "Alien", icon: "👽", value: ":alien:" },
    { name: "Beers", icon: "🍻", value: ":beers:" },
    { name: "Coffee", icon: "☕", value: ":coffee:" },
    { name: "Construction", icon: "🚧", value: ":construction:" },
    { name: "Worker", icon: "👷", value: ":construction_worker:" },
    { name: "Recycle", icon: "♻️", value: ":recycle:" },
    { name: "Rewind", icon: "⏪", value: ":rewind:" },
    { name: "Package", icon: "📦", value: ":package:" },
    { name: "Boom", icon: "💥", value: ":boom:" },
    { name: "Label", icon: "🏷️", value: ":label:" },
    { name: "Briefcase", icon: "💼", value: ":briefcase:" },
    { name: "Building", icon: "🏗️", value: ":building_construction:" },
    { name: "Poop", icon: "💩", value: ":poop:" },
    { name: "merge", icon: "🔀", value: ":twisted_rightwards_arrows:" },
    { name: "Coffin", icon: "⚰️", value: ":coffin:" },
];